#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Coursequestionbank::Application.load_tasks

task :default => [:test]

desc "Clean cached file generated by server run. Do it before commit."
task :clean do
  sh "git clean -d -fx"
end

desc "Set up sunspot before running App on C9."
task :run do
  sh "bundle exec sunspot-solr start -p 8983"
end

desc "Shut sunspot off before running any migrations"
task :stop do
  sh "bundle exec sunspot-solr stop"
end